server:
  port: 8083
spring:
  application:
    name: =STOCKEXCHANGE-WS
  datasource:
    password: root
    url: jdbc:h2:mem:testdb
    username: root
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
  cloud:
    config:
      uri: http://localhost:8090
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:7777
logging:
  level:
    org.springframework.web: DEBUG
eureka:
  client:
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
