eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8888
spring:
  application:
    name: ZUUL-WS
  cloud:
    config:
      uri: http://localhost:8090

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:7777